### ISSUE TITLE
I am so happy right now

### ISSUE THREAD

**Issue by nebulade** [Schneegans/Burn-My-Windows#1]
Please close after reading, so I just wanted to thank you very much to bring this to gnome after the cube. I have missed compiz/beryl for long sad years and I personally lack the shader foo or also have never ventured into such corners of a system.

Now as a feature request, if I may ask, is is possible to change the fire colors? Already now it is magnificent :)

**Comment by Schneegans** [comment]
Thanks for the kind words! Indeed, this will be the thing to implement next. The difficulty will be to create a proper Gtk.Widget for configuring this, since it's not only one color but rather a gradient (five colors currently, white -> yellow -> orange -> red -> transparent gray). And the color steps are not distributed evenly. So we will need some kind of gradient editor....

**Comment by Schneegans** [comment]
I just implemented this in the `main` branch!

**Comment by nebulade** [comment]
wow this is awesome, thank you. For some reason however if I change the colors, the effect stays the same. The values however are preserved within the extension config screen. Unfortunately I have no clue how to debug such things within the gnome-shell.

**Comment by nebulade** [comment]
doh...since the settings already appeared, I haven't thought of a gnome-shell restart. But yes I can confirm it works beautifully now.

**Comment by Schneegans** [comment]
Just released it on EGO!
