### ISSUE TITLE
disable open window animation with focus (gnome extension)

### ISSUE THREAD

**Issue by tourmaline3333** [Schneegans/Burn-My-Windows#117]
Burn my windows do not animation open window animation when I use with "Focus" extension.
https://extensions.gnome.org/extension/3924/focus/

1. set "Open Window Animation".
2. run "open window animation". -> no problem.
3. set "Focus" extension to True.
4. cannot run Open Window Animation.

* Should I consult with Focus team?

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. On which GNOME version are you? I just tested it on GNOME 40 and everything seems to work as expected.

**Comment by tourmaline3333** [comment]
Thank you for your quick response!
my environment is below.

Gnome:3.36.8
OS:Zorin OS 16 x64

**Comment by Schneegans** [comment]
If another extension tweaks the animations of an opening window, that's likely to interfere with Burn-My-Windows. However, the version of Focus I installed, does not seem to do this. Are you using the most recent version of Focus? That's kind of interesting anyways, as the Focus extension never officially supported GNOME 3.36...

**Comment by tourmaline3333** [comment]
>That's kind of interesting anyways, as the Focus extension never officially supported GNOME 3.36...
>
Sorry,maybe my gnome is 3.38.4.
--------
$ cat /usr/share/gnome/gnome-version.xml 
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>36</minor>
 <micro>8</micro>
 <distributor>Ubuntu</distributor>
 
</gnome-version>⏎  

$ gnome-shell --version
GNOME Shell 3.38.4
-------
Zorin OS 16 core use Gnome GNOME Shell 3.38. written in this site.
https://www.makeuseof.com/zorin-os-16-released-see-whats-new/

>Are you using the most recent version of Focus?
>
Yes.I installed latest Focus version 7, 2 days ago.

**Comment by tourmaline3333** [comment]
I found that open animation is enabled case.

enable open window animation below case
- any application's sub window, 
   ex)VSCode : ctrl + shift + s. open save as window 

disable open window animation below case
- open new application window
- open Guake turminal

**Comment by Schneegans** [comment]
I looked through their code and couldn't find anything suspicious, which would explain a different behavior on GNOME 3.38. So I guess that something was changed in Clutter with GNOME 40 which caused this issue.

Thanks again for the report, but this seems to be an incompatibility with one specific other extension which is already fixed with more up-to-date GNOME versions (GNOME 40 has been released a year ago, the current version is GNOME 42). So I hope that you understand that I'll invest my limited spare time in fixing more crucial bugs and developing new features :wink:
