### ISSUE TITLE
Wisps effect seems broken on Kwin

### ISSUE THREAD

**Issue by namesarebloat** [Schneegans/Burn-My-Windows#199]
https://gfycat.com/inexperiencedfortunatefluke (sorry for the crappy quality, obs doesn't work on my laptop)

I tried all the other effects, they work.

Sys info:

Operating System: Fedora Linux 36  
KDE Plasma Version: 5.25.4  
KDE Frameworks Version: 5.97.0  
Qt Version: 5.15.5  
Kernel Version: 5.18.16-200.fc36.x86_64 (64-bit)  
Graphics Platform: X11  
Processors: 2 × Intel® Core™2 Duo CPU P8400 @ 2.26GHz  
Memory: 3,7 GiB of RAM  
Graphics Processor: Mesa Mobile Intel® GM45 Express Chipset

**Comment by Schneegans** [comment]
Hi there! Thanks for the report! Sadly, I cannot reproduce this on my end. It could be due to an issue with your GPU (I only have an NVidia card for testing). Do you have by any chance some coding experience so that we could try to debug this on your end?

The shaders should be stored in ~/.local/share/kwin/effects/kwin4_effect_wisps/contents/shaders. There are two files, which one is used, depends on your system. Usually it should be wisps_core.frag. If you feel comfortable editing these shaders, we could try to find the issue!

**Comment by Schneegans** [comment]
In this case I guess we have to wait until someone else encounters a similar issue. Btw, have you tried using Wayland instead?

**Comment by Schneegans** [comment]
Thanks to @daudix-UFO, this issue has been resolved! Feel free to clone the latest version from git. [There's a guide in the README](https://github.com/Schneegans/Burn-My-Windows#c-cloning-the-latest-version-with-git-1). Or wait for the next release...
