### ISSUE TITLE
Randomizing Effects/Animations

### ISSUE THREAD

**Issue by shawnk0723** [Schneegans/Burn-My-Windows#200]
Schneegans,

Is there any way to make all these effects work randomly instead of setting just one animation at a time in KDE? I really miss that feature from compiz. I know this is already possible in Gnome. You've already said it should be a feature of kwin but how difficult would it be to add randomizing anim option to the current burn-my-windows setting in kwin? Would there be any easier way of doing this by somehow importing/mimicking this code from Gnome and make it run randomly inside KDE? I'm sure adding this option will encourage kde users to wanna use BMW more.

**Comment by Schneegans** [comment]
Hi there! Randomizing is one thing which would be nice, another cool thing would be to be able to choose different animations for opening / closing. Many of the animations work great for window closing but are a bit annoying for opening windows.

I _could_ be possible to create a single "Burn-My-Windows" effect for KWin (instead of individual effects for _Fire_, _Hexagon_, etc). This effect could then have a complex settings dialog similar to the preferences dialog in GNOME.There you could choose which effects should be used. However, this approach has some drawbacks:
* I am not sure if this would be actually possible. AFAIK, the API for KWin effects is not designed to be used like this. There's a lot of magic happening in the background and I guess that a lot of hacks could be required to squish multiple effects into something which should be only one effect.
* It would not be possible to combine the BMW effects with the existing effects of KWin. So if you would like to use the standard slide or fade animation for window opening but a BMW effect for window closing, this would be impossible.

On the flip-side, if KWin supported randomizing effects or choosing different effects for opening and closing, all would be solved. So IMHO, this would be a much cleaner solution!

**Comment by Schneegans** [comment]
Btw, #173 is closely related to this request.

**Comment by shawnk0723** [comment]
> Hi there! Randomizing is one thing which would be nice, another cool thing would be to be able to choose different animations for opening / closing. Many of the animations work great for window closing but are a bit annoying for opening windows.
> 
> I _could_ be possible to create a single "Burn-My-Windows" effect for KWin (instead of individual effects for _Fire_, _Hexagon_, etc). This effect could then have a complex settings dialog similar to the preferences dialog in GNOME.There you could choose which effects should be used. However, this approach has some drawbacks:
> 
> * I am not sure if this would be actually possible. AFAIK, the API for KWin effects is not designed to be used like this. There's a lot of magic happening in the background and I guess that a lot of hacks could be required to squish multiple effects into something which should be only one effect.
> * It would not be possible to combine the BMW effects with the existing effects of KWin. So if you would like to use the standard slide or fade animation for window opening but a BMW effect for window closing, this would be impossible.
> 
> On the flip-side, if KWin supported randomizing effects or choosing different effects for opening and closing, all would be solved. So IMHO, this would be a much cleaner solution!

@Schneegans 

"another cool thing would be to be able to choose different animations for opening / closing. Many of the animations work great for window closing but are a bit annoying for opening windows."

**That would be another great addition to BMW but I personally think randomizing should be first priority than this.**

"I could be possible to create a single "Burn-My-Windows" effect for KWin (instead of individual effects for Fire, Hexagon, etc). This effect could then have a complex settings dialog similar to the preferences dialog in GNOME.There you could choose which effects should be used. However, this approach has some drawbacks:"

**this sounds nice If you think that's possible. I'm willing to test it for you on my machine if you can release this version as a beta/prototype.:)**

"It would not be possible to combine the BMW effects with the existing effects of KWin. So if you would like to use the standard slide or fade animation for window opening but a BMW effect for window closing, this would be impossible."

**I used to use existing animations of kwin but after installing BMW I disabled them because it felt rather awkward running them at the same time.**

"On the flip-side, if KWin supported randomizing effects or choosing different effects for opening and closing, all would be solved. So IMHO, this would be a much cleaner solution!"

**Has anyone submitted this as feature request to kwin? If not, where can you submit it?**

**Comment by Schneegans** [comment]
Btw, there is this related feature request by now: https://bugs.kde.org/show_bug.cgi?id=464322.

**Comment by Schneegans** [comment]
I'll close this issue, as this is not really in the scope of Burn-My-Windows on KDE. Let's hope that the above feature request gets some attention!
