### ISSUE TITLE
[Feature Request] More animations?

### ISSUE THREAD

**Issue by Tuxino88** [Schneegans/Burn-My-Windows#22]
I congratulate you for the great job!
Can you develop a single extension that rags what were the most famous animations of compiz? (WOOBLY, CUBE, minimize, maximize etc. for example).

**Comment by Schneegans** [comment]
Thanks for the kind words!

You probably know this, but we already have extensions for the [cube effect](https://extensions.gnome.org/extension/4648/desktop-cube/), for the [magic lamp](https://extensions.gnome.org/extension/3740/compiz-alike-magic-lamp-effect/), and for [wobbly windows](https://extensions.gnome.org/extension/2950/compiz-alike-windows-effect/). Creating a single extension which basically merges all of these is probably a bad idea. I can understand that from a users perspective it may be convenient to install just one extension instead of several, however there are plenty of good reasons to not do this:
* **More likely to break:** The bigger an extension gets, there more likely it breaks with GNOME Shell updates. If it is split into several extensions, some of them may continue to work without needing an update.
* **Slower Updates:** If one effect is very difficult to port to a new GNOME Shell version, the entire extension will not be available on the new GNOME Shell version until the porting is completed.
* **Single Point of Failure:** If the developer of the one big extension has no time to work on it, nothing will be updated, fixed, or ported to new GNOME versions.

I believe that it is best if extensions are as small as possible, mess as little as possible with GNOME Shell's source code, and are dedicated to one specific purpose. Otherwise they will break frequently which will lead to a bad user experience...

**Comment by Tuxino88** [comment]
true, you are right.
