### ISSUE TITLE
Not working on Kubuntu 22.04 LTS

### ISSUE THREAD

**Issue by mytricker0** [Schneegans/Burn-My-Windows#247]
as I said it's not working. I think it is because it uses kwin 5.24.7 so I installed another version: the 5.25.5. And the issue is still the same. I can select it in my desktop effects but it does not work even to I apply it

![image](https://user-images.githubusercontent.com/58003204/203863658-949a861d-5c19-4962-bd0d-8a6630a8402b.png)

**Comment by Schneegans** [comment]
Thanks for the report. The effects should be working with this version. Have you restarted your system? Have you tried running `journalctl -f -o cat` in a terminal while selecting + applying one of the effects? Is some error message printed?

**Comment by mytricker0** [comment]
my bad I didn't restart the system. For those who have the same problem, just do 
`sudo add-apt-repository ppa:kubuntu-ppa/backports-extra`
`sudo apt update`
`sudo apt full-upgrade -y`

it will upgrade your plamsa version from 5.24.7 to 5.25.5
the restart your system 
`reboot`

**Comment by naikrathan** [comment]
lol!! i fought for these effects for straight 10 hours ...next day i came to know that in settings it was turned off..it was disabled on battery power!!

**Comment by frugaltech** [comment]
Hi.

I am reviving this thread because I am having a hard time making any of these super nice effects work. I get this when I try to apply Portal [Burn-My-Windows] in Kubuntu 22.04 with backports enabled as suggested in this thread:
<snip>
QQuickVelocityCalculator: a call to stopMeasuring() must be preceded by a call to startMeasuring()
"Could not convert argument 1 at"
         "onTriggered@file:///usr/share/kpackage/kcms/kcm_kwin_effects/contents/ui/Effect.qml:129"
         "onClicked@file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/templates/SwipeListItem.qml:524"
"Passing incompatible arguments to C++ functions from JavaScript is dangerous and deprecated."
"This will throw a JavaScript TypeError in future releases of Qt!"
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60468, resource id: 98566308, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60480, resource id: 98566308, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60481, resource id: 98566308, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60482, resource id: 98566308, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60483, resource id: 98566308, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60484, resource id: 98566308, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60485, resource id: 98566308, major code: 7 (ReparentWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60486, resource id: 98566308, major code: 6 (ChangeSaveSet), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60487, resource id: 98566308, major code: 2 (ChangeWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 60488, resource id: 98566308, major code: 10 (UnmapWindow), minor code: 0
file:///usr/share/kpackage/kcms/kcm_kwin_effects/contents/ui/main.qml:22:13: QML ColumnLayout: Cannot anchor to an item that isn't a parent or sibling.
file:///usr/share/kpackage/kcms/kcm_kwin_effects/contents/ui/main.qml:56:17: QML MenuItem: Binding loop detected for property "implicitWidth"
file:///usr/share/kpackage/kcms/kcm_kwin_effects/contents/ui/main.qml:64:17: QML MenuItem: Binding loop detected for property "implicitWidth"
libkwinglutils: Failed to compile fragment shader:
 "0(77) : error C0153: floating point constant overflow\n\x00"
kwin_scripting: /home/lars/.local/share/kwin/effects/kwin4_effect_portal/contents/code/main.js:74: error: Failed to set uniform uDuration
</snip>

What am I missing here?

/Lars

**Comment by Schneegans** [comment]
@frugaltech: This error should have been fixed with the latest update released two days ago. Are you on version 37 already?

**Comment by frugaltech** [comment]
Ah - the plot thickens. I just created a new user account and it works perfectly. So it seems there is something not quite right with the update of the screen effects. I also tried uninstalling the effects and reinstalling but that did not make a difference on the affected account. Can you point me to the local files? Then I'll try deleting manually and then see where that takes me.

/Lars
