### ISSUE TITLE
Certain effects do not take up the entire screen

### ISSUE THREAD

**Issue by FelixFourcolor** [Schneegans/Burn-My-Windows#328]
Energize A, Energize B, Fire, and Wisps, when the window opens/closes in full screen, do not draw their animation over the entire screen. 

![screenshot](https://user-images.githubusercontent.com/34260584/230763220-0a32cd8c-1c32-48b4-87a9-b8b89b5e0bc0.png)

The screenshot shows what happens when I open VScode in full screen, using the Fire effect. (This problem is not particular to VScode, it's just an example). The animation leaves a tiny margin around the edges. And similarly when I close the app from full screen. I used Fire to demonstrate the bug, but this is also the case for Energize A, Energize B, and Wisps. And this only affects full screen apps.

No other extensions were running when I took the screenshot.

System info:
- Arch linux
- Gnome 43.4
- X11
- Burn My Windows v.30
- Display resolution: 4K

**Comment by Schneegans** [comment]
Hi there! Thanks for the report! This is more or less expected behavior. In order to avoid any harsh borders, these effects are faded towards the window border. On unmaximized windows, the actual window border is pretty far away since the window's shadow is also included. So the fading happens approximately over the shadow region. Maximized windows do not have a shadow, so that fading already happens over the window itself.

I think it should be possible to disable the fading on maximized windows in order to solve this issue. This shouldn't be too hard to implement, but I have some other things with a higher priority on my to-do list :smile: So if anybody wants to implement this, just drop a note here and I can provide some pointers!
