### ISSUE TITLE
Matrix effect add random start/end

### ISSUE THREAD

**Issue by artur-woocode** [Schneegans/Burn-My-Windows#35]
## The Motivation
Right now when closing the window you clearly see where the letters start and animation ends, adding some bit of variance on the start/end position would make it the lines be blurred i think.

## The Solution
I think adding a slider maybe that will add a bit of randomness when the letters start end for the columns.

## The Alternatives
Maybe just add some random value for start end without a slider as a beginning.

**Comment by Schneegans** [comment]
Thank you for the suggestion!

However, I do not fully understand what aspect of the animation should be randomized. Could you maybe try to visualize (e.g. with a crude sketch or something) what the effect should look like? Do you mean a random vertical offset, so that some of the rain drops start dropping some hundred pixels above the window and some drop further beyond the bottom edge of the window...?

**Comment by artur-woocode** [comment]
> Do you mean a random vertical offset, so that some of the rain drops start dropping some hundred pixels above the window and some drop further beyond the bottom edge of the window...?

Correct, right now it looks something like this when the animation is finished, creates a perfect rectangle 
![image](https://user-images.githubusercontent.com/47351527/148729997-619027b6-d560-46a7-bebb-223ead94b668.png)

I think adding a bit more random start and end for the drops would help with the illusion
