### ISSUE TITLE
GLib.FileError: Failed to open file

### ISSUE THREAD

**Issue by wildcard-f8** [Schneegans/Burn-My-Windows#396]
## Describe the Bug
I can't turn the extension on.

The settings of extension burn-my-windows@schneegans.github.com had an error:
```
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/schemas/gschemas.compiled”: open() failed: No such file or directory
```

Stack trace:
```
getSettings@resource:///org/gnome/Shell/Extensions/js/extensions/sharedInternals.js:100:53
fillPreferencesWindow@file:///usr/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:141:27
_loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:36:18
async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

1. Go to 'Extensions'
3. Scroll down to 'Burn My Windows'

You may also check the output of GNOME Shell for any error messages.
This can be done with the following terminal command.
Execute this in a terminal and observe the output while reproducing the bug.

```bash
journalctl -f -o cat | grep -E 'burn-my-windows|'
```

## System
_Please complete the following information:_
 - Linux distribution [MANJARO x86_64 23.1.0 Vulcan]
 - Burn-My-Windows version [gnome-shell-extension-burn-my-windows 38-1]
 - GNOME Shell version: [GNOME Shell 45.0]

**Comment by Schneegans** [comment]
Hi there! This is most likely an issue with the packaging. Since GNOME 45, these compiled schema files are not to be distributed anymore with the extensions as they are somewhat platform-dependent. They are rather generated on-the-fly when the extension is installed with `gnome-extensions install <zip file>`. If the extension is not installed with this command or from extensions.gnome.org, but from a package, the schemas need to generated in a post-install step.

You can also read this related issue: https://github.com/Schneegans/Fly-Pie/issues/317#issuecomment-1748655766
