### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by KjshServer** [Schneegans/Burn-My-Windows#53]
![Captura de pantalla de 2022-01-17 19-03-57](https://user-images.githubusercontent.com/62609310/149849740-8253e9e8-e4a7-413a-8e98-57ae6a9ec8c1.png)

OS: Ubuntu 21.10 x86_64
DE: GNOME 40.5

**Comment by JSybrandt** [comment]
Also got the same error.

```
uname -a

> Linux pop-os 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux
```

```
gnome-shell --version

> GNOME Shell 40.5
```

**Comment by Schneegans** [comment]
Maybe you have to logout / login after the update?

**Comment by axkg** [comment]
Can confirm: restarting gnome-shell (Alt+F2 "r") fixed it for me.

**Comment by IsaacDias2020** [comment]
All working here, after update Gnome.
Awesome new effect (Beam me up, Scotty...lol).
Greetings from Brazil.

**Comment by KjshServer** [comment]
> ¿Tal vez tenga que cerrar sesión/iniciar sesión después de la actualización?

**Comment by bksubhuti** [comment]
today got.. now cannot delete and install etc
![image](https://user-images.githubusercontent.com/18184280/169672543-938b687f-abe9-468b-91b8-c09134d68c87.png)

**Comment by Schneegans** [comment]
Have you tried to logout / login after the update?

**Comment by bksubhuti** [comment]
ah.. yes.. in between emails, I have shut down and my windows are exploding again.
It would be good if a message could be displayed instead of "error".  This would probably be a task for the extension team rather than the individuals.
I wish extensions were like KDE.. so much easier, but KDE does not work with vscode and github keys, so I use ubuntu 22.04

Love your app.. sadhu x 3
